# -*- coding: utf-8 -*-
"""WorkShopDataWareHouse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zwc6Bp-MPjolAY33xjsgYmO6FECxG_Wa

**Phase 1 Extract**
"""

import pandas as pd
import sqlite3

# โหลดข้อมูลดิบ
df_raw = pd.read_csv('raw_ecommerce_data.csv')

# ตรวจสอบโครงสร้างและค่า Null
df_raw.info()  # เช็ค Data Types และ Missing Values ก่อนเสมอ
df_raw.head()

"""**Phase 2A Transfrom**"""

# สร้าง dim_customer พร้อมลบแถวที่มีค่าว่าง (Missing Value) ออกก่อน
dim_customer = (
    df_raw[['Customer_Name', 'Email']]
    .dropna(subset=['Customer_Name', 'Email'])  # ลบแถวที่มีค่า NULL ในคอลัมน์เหล่านี้
    .drop_duplicates()
)

# สร้าง Surrogate Key (customer_id)
dim_customer = dim_customer.reset_index(drop=True)
dim_customer['customer_id'] = dim_customer.index + 1

# จัดเรียงคอลัมน์ให้ PK อยู่หน้าสุด
dim_customer = dim_customer[['customer_id', 'Customer_Name', 'Email']]

# สร้าง dim_product
dim_product = df_raw[['Product', 'Category']].drop_duplicates().reset_index(drop=True)

# สร้าง Surrogate Key (product_id)
dim_product['product_id'] = dim_product.index + 1

# จัดเรียงคอลัมน์ให้ PK อยู่หน้าสุด
dim_product = dim_product[['product_id', 'Product', 'Category']]

# แปลงคอลัมน์วันที่เป็น datetime และดึงวันที่ไม่ซ้ำกัน
dates = pd.to_datetime(df_raw['Order_Date'], format='mixed', errors='coerce').dropna().unique()

dim_date = pd.DataFrame({'full_date': dates}).sort_values('full_date').reset_index(drop=True)

# สร้าง date_id (เช่น 20260424) และแตกรายละเอียดวัน/เดือน/ปี
dim_date['date_id'] = dim_date['full_date'].dt.strftime('%Y%m%d').astype(int)
dim_date['day'] = dim_date['full_date'].dt.day
dim_date['month'] = dim_date['full_date'].dt.month
dim_date['month_name'] = dim_date['full_date'].dt.month_name()
dim_date['quarter'] = 'Q' + dim_date['full_date'].dt.quarter.astype(str)
dim_date['year'] = dim_date['full_date'].dt.year

# จัดเรียงคอลัมน์
dim_date = dim_date[['date_id', 'full_date', 'day', 'month', 'month_name', 'quarter', 'year']]

"""**Phase 2A Transfrom**"""

# 1. Join กับ dim_customer
fact_sales = pd.merge(df_raw, dim_customer, on=['Customer_Name', 'Email'], how='left')
fact_sales = fact_sales.drop(columns=['Customer_Name', 'Email'])

# 2. Join กับ dim_product
fact_sales = pd.merge(fact_sales, dim_product, on=['Product', 'Category'], how='left')
fact_sales = fact_sales.drop(columns=['Product', 'Category'])

# 3. Join กับ dim_date
# 1. แปลง Order_Date ใน fact_sales ให้เป็น datetime64 ก่อน
fact_sales['Order_Date'] = pd.to_datetime(fact_sales['Order_Date'], format='mixed', errors='coerce')

# 2. ทำการ Join กับ dim_date ตามปกติ
fact_sales = pd.merge(fact_sales, dim_date, left_on='Order_Date', right_on='full_date', how='left')

# 3. ลบคอลัมน์วันที่ที่ไม่จำเป็นออก
fact_sales = fact_sales.drop(columns=['Order_Date', 'full_date'])

# Remove duplicates based on 'Order_ID' to prevent IntegrityError
fact_sales = fact_sales.drop_duplicates(subset=['Order_ID'], keep='first')

# 4. เลือกเฉพาะคอลัมน์ที่จำเป็นสำหรับ fact_sales table ในฐานข้อมูล
fact_sales = fact_sales[['Order_ID', 'customer_id', 'product_id', 'date_id', 'Quantity', 'Unit_Price', 'Amount']]

"""**Phase 3A/3B Load**"""

import sqlite3

# 1. สร้าง Connection ไปที่ไฟล์ database
conn = sqlite3.connect('warehouse.db')
cursor = conn.cursor()

# เปิดใช้งาน Foreign Keys Constraint ใน SQLite
cursor.execute("PRAGMA foreign_keys = ON;")

# 2. สร้างตารางทั้งหมด (Schema Creation)
cursor.executescript('''
    -- ตาราง Dimension: Customer
    CREATE TABLE IF NOT EXISTS dim_customer (
        customer_id INTEGER PRIMARY KEY,
        Customer_Name TEXT NOT NULL,
        Email TEXT
    );

    -- ตาราง Dimension: Product
    CREATE TABLE IF NOT EXISTS dim_product (
        product_id INTEGER PRIMARY KEY,
        Product TEXT NOT NULL,
        Category TEXT
    );

    -- ตาราง Dimension: Date
    CREATE TABLE IF NOT EXISTS dim_date (
        date_id INTEGER PRIMARY KEY,
        full_date TEXT NOT NULL UNIQUE,
        day INTEGER,
        month INTEGER,
        month_name TEXT,
        quarter TEXT,
        year INTEGER
    );

    -- ตาราง Fact Table: Sales
    CREATE TABLE IF NOT EXISTS fact_sales (
        Order_ID TEXT PRIMARY KEY,
        customer_id INTEGER REFERENCES dim_customer(customer_id),
        product_id INTEGER REFERENCES dim_product(product_id),
        date_id INTEGER REFERENCES dim_date(date_id),
        Quantity INTEGER,
        Unit_Price REAL,
        Amount REAL
    );
''')

# บันทึกการเปลี่ยนแปลงและปิด Connection
conn.commit()
conn.close()

print("สร้างตารางทั้งหมดเรียบร้อยแล้ว!")

"""**Phase 3 Load**"""

# 1. สร้าง Connection และเปิดใช้งาน Foreign Key (ต้องสร้างใหม่เนื่องจากปิดไปแล้วในเซลล์ที่แล้ว)
conn = sqlite3.connect('warehouse.db')
conn.execute("PRAGMA foreign_keys = ON;")
cursor = conn.cursor()

# Clear existing data from dimension and fact tables before appending to avoid IntegrityError
cursor.execute("DELETE FROM dim_customer;")
cursor.execute("DELETE FROM dim_product;")
cursor.execute("DELETE FROM dim_date;")
cursor.execute("DELETE FROM fact_sales;") # Also clear fact_sales if it's meant to be a full reload
conn.commit() # Commit the deletions

# โหลดข้อมูล Dimensions ทั้งหมด
dim_customer.to_sql('dim_customer', con=conn, if_exists='append', index=False)
dim_product.to_sql('dim_product', con=conn, if_exists='append', index=False)
dim_date.to_sql('dim_date', con=conn, if_exists='append', index=False)

# โหลดข้อมูล Fact Table (เลือกเฉพาะคอลัมน์ที่ตรงกับโครงสร้าง SQLite)
fact_sales_db = fact_sales[['Order_ID', 'customer_id', 'product_id', 'date_id', 'Quantity', 'Unit_Price', 'Amount']]
fact_sales_db.to_sql('fact_sales', con=conn, if_exists='append', index=False)

# ยืนยันการบันทึก
conn.commit()

# ปิด Connection หลังการใช้งาน
conn.close()

print('ETL Pipeline ran successfully!')

query = """
SELECT
    c.Customer_Name,
    SUM(f.Amount) as Total_Spend
FROM fact_sales f
JOIN dim_customer c ON f.customer_id = c.customer_id
GROUP BY c.Customer_Name
ORDER BY Total_Spend DESC
LIMIT 3;
"""

# เชื่อมต่อฐานข้อมูลและดึงผลลัพธ์ออกมาเป็น DataFrame
with sqlite3.connect('warehouse.db') as conn:
    df_top_customers = pd.read_sql_query(query, conn)

print("Top 3 Customers by Total Spend:")
print(df_top_customers)